name: fiber_photometry

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - h5py
  - hdf5
  - ipywidgets
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pyqt
  - pytables
  - qt=5
  - qtconsole
  - qtpy
  - scikit-learn
  - scipy
  - tqdm

  - pip:
    - openpyxl
    - hmmlearn
    - ipympl
