name: fiber_photometry
channels:
  - defaults
dependencies:
  -pip
  - h5py
  - hdf5
  - ipywidgets
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pyqt
  - pytables
  - python=3.8
  - qt=5
  - qtconsole
  - qtpy
  - scikit-learn
  - scipy
  - tqdm

  - pip:
    - openpyxl
    - hmmlearn
    - ipympl
